/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.totem.sim;

/**
 *
 * @author Aluno
 */
public class TelaInicial extends javax.swing.JPanel {

    /** Creates new form Tela1 */
    public TelaInicial() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Bem vindo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 11, -1, -1));

        jLabel3.setMaximumSize(new java.awt.Dimension(126, 126));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 43, -1, 153));

        jLabel4.setText("Insira seu bilhete único para iniciar ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel6.setText("[logo visa]");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 85, 41));

        jLabel7.setText("[logo mastercard]");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 41));

        jLabel5.setText("cartões aceitos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 85, 41));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
